config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :games, only: [:new, :create, :show] do
    %i(join deal start_bidding bid pass trump start_game play restart).each do |action|
      post action, to: "games##{action}", as: action
    end

    get :data, to: 'games#data', as: :data
  end
  resources :user_names, only: [:index, :create]
end

app/models/shelem/game.rb
module Shelem
  class Game
    include Minifier
    include Enums

    PROPS = %i(
      game_suit_i game_scores cards_played
      current_round last_round
    )

    enum game_suit: Playing::Card::SUITS

    def initialize(
      game_suit_i: nil,
      game_scores: [0, 0],
      cards_played: 0,
      current_round: nil,
      last_round: nil
    )
      @game_suit_i = game_suit_i
      @game_scores = game_scores
      @cards_played = cards_played
      @current_round = current_round.present? ? Shelem::Round.parse(current_round) : Shelem::Round.new
      @last_round = Shelem::Round.parse(last_round) if last_round.present?
    end

    attr_reader *PROPS

    def data
      {
        game_suit_i: game_suit_i,
        game_scores: game_scores,

        cards_played: cards_played,

        current_round: current_round&.to_h,
        last_round: last_round&.to_h,
      }
    end

    def next_to_play
      (current_round.lead + cards_played) % 4
    end

    def rounds_played
      (cards_played / 4.0).ceil
    end

    def play(player_sets, card)
      cards_in_hand = player_sets[next_to_play]

      # does the player have the card in hand?
      unless cards_in_hand.delete(card)
        raise 'INVALID CARD PLAYED'
      end

      if current_round.new?
        current_round.suit_i = card.suit_i
        @game_suit_i = card.suit_i unless @game_suit_i
      else
        # can the player has a card for current_round.suit but not playing it
        if current_round.suit && card.suit != current_round.suit && cards_in_hand.include_suit?(current_round.suit)
          raise 'MUST PLAY LEAD SUIT'
        end
      end

      @cards_played += 1
      current_round.cards << card
      finish_round if current_round.finished?
    end

    def finished?
      cards_played == 48
    end

    def finish_round
      # find winner
      round_winner = find_round_winner
      round_winner_team = round_winner % 2

      # count score
      game_scores[round_winner_team] += current_round.score

      # reset round
      @last_round = current_round
      @current_round = Shelem::Round.new(lead: round_winner)
    end

    def find_round_winner
      current_round.flat_cards.map do |card|
        # has player cut hand with a game suit?
        if current_round.suit != game_suit && card.suit == game_suit
          # add 100 to ensure it's gonna be higher than any of the round suit ranks
          card.rank + 100
        else
          card.suit == current_round.suit ? card.rank : -1
        end
      end.each_with_index.max[1]
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  ADMIN_ACTIONS = %i(deal start_bidding start_game restart)
  PLAYER_ACTIONS = %i(join bid pass trump play)

  before_action :ensure_user_uid
  before_action :ensure_admin!, only: ADMIN_ACTIONS
  after_action :publish_event, only: PLAYER_ACTIONS + ADMIN_ACTIONS

  around_action :log_to_statsd

  def show
    return render :not_found unless game

    @game_uid = game_uid
    @game = game
    @view_data = view_data
  end

  def data
    render json: view_data
  end

  def create
    game = ShelemGame.new(admin_uid: user_uid).tap do |game|
      game.add_player!(user_uid, user_name)
    end

    uid = game.save!
    redirect_to game_path(uid)
  end

  def join
    change_game { |g| g.add_player!(user_uid, user_name) }
  end

  def deal
    change_game { |g| g.deal! }
  end

  def start_bidding
    change_game { |g| g.start_bidding! }
  end

  def bid
    change_game { |g| g.bid!(user_uid, params.require(:raise)) }
  end

  def pass
    change_game { |g| g.pass!(user_uid) }
  end

  def trump
    change_game { |g| g.trump!(user_uid, params.fetch(:cards_in, []), params.fetch(:cards_out, [])) }
  end

  def start_game
    change_game { |g| g.start_game! }
  end

  def play
    change_game { |g| g.play!(user_uid, params.require(:card)) }
  end

  def restart
    change_game { |g| g.restart! }
  end

  private

  def log_to_statsd
    tags = ['action:%s' % params[:action]]
    STATSD.time('game.action.time', tags: tags) do
      STATSD.increment('game.action.count', tags: tags)
      yield
    end
  end

  def change_game
    yield(game)
    game.save!(game_uid)
    render json: view_data
  end

  def publish_event
    return unless game.players
    game.players.uids.each_with_index(&method(:publish_to_player))
  end

  def publish_to_player(uid, index)
    ActionCable.server.broadcast(
      "game_#{game_uid}_#{index}",
      body: view_data(uid).to_json
    )
  end

  def ensure_admin!
    render status: :unauthorized unless user_uid == game.admin_uid
  end

  def view_data(player_uid = user_uid)
    ShelemGameSerializer.new(game, game_uid, player_uid).to_h
  end

  def game_uid
    params[:game_id] || params.require(:id)
  end

  def game
    @_game ||= ShelemGame.find(game_uid)
  end

  def ensure_user_uid
    unless [user_name, user_uid].all?(&:present?)
      redirect_to user_names_path(return_to: request.path)
    end
  end
end

app/views/games/new.erb
<% content_for :head do %>
  <script src='https://www.google.com/recaptcha/api.js?hl=fa'></script>
<% end %>

<script>
  function recaptchaCallback() {
    document.forms[0].submit()
  }
</script>

<h2>
  <%= t('start_new_game.title') %>
</h2>

<%= form_with scope: :game, url: games_path, local: true do %>
  <div class="g-recaptcha" data-callback="recaptchaCallback" data-sitekey="6LcW2IYUAAAAAFEeOJ3l3NqbxntRM3nzR6JDLeAF"></div>
<% end %>

app/views/games/not_found.erb
<p>
  <%= t('not_found.title') %>
</p>

<a class='button' href='/games/new'>
  <%= t('home_page.start_new_game') %>
</a>

app/views/games/show.erb
<% content_for :head do %>
  <meta name="game-uid" content="<%= @game_uid %>">
  <meta name="player-index" content="<%= @view_data.dig(:player, :index) %>">
  <meta name="vue-data" content="<%= @view_data.to_json %>">
<% end %>

<div id='vue-app'>
  <!-- <pre>{{ player }}</pre> -->
  <div v-if='player.joined'>
    <div class='game-info'>
      <h4>
        <span class='info'>
          ({{ game.total_scores[0] }}) &mdash; {{ game.total_games }} &mdash; ({{ game.total_scores[1] }})
        </span>
      </h4>
      <h4>
        <div class='my-team'>
          <div v-for='player in game.players.filter((i, ix) => ix % 2 == 0)' class='player-card'>
            <player v-bind:data='player'></player>
          </div>
          <span v-if="game.scores" class='info'>
            {{ game.scores[0] }}
            <span v-if="(game.highest_bidder % 2) == 0">
              <%= t('game.playing.of') %> {{ game.highest_bid }}
            </span>
          </span>
        </div>
        <div class='other-team'>
          <span v-if="game.scores" class='info'>
            {{ game.scores[1] }}
            <span v-if="(game.highest_bidder % 2) == 1">
              <%= t('game.playing.of') %> {{ game.highest_bid }}
            </span>
          </span>
          <div v-for='player in game.players.filter((i, ix) => ix % 2 == 1)' class='player-card'>
            <player v-bind:data='player'></player>
          </div>
        </div>
      </h4>
    </div>

    <div v-if="game.status == 'to_name'">
      <h4><%= t('game.to_name.title') %></h4>
      <div v-if='player.admin'>
        <h4><%= t('game.to_name.share_link') %></h4>
        <div class='share-link'>
          <input id='foo' type='text' readonly='true' value='<%= game_url(@game_uid) %>' />
          <button class="clipboard-btn" data-clipboard-target="#foo">
            <%= t('game.to_name.copy_link') %>
          </button>
        </div>
      </div>
    </div>
    <div>
      <div v-if="typeof game.next_to_play === 'number'">
        <h4>
          <%= t('game.playing.played_set') %>
        </h4>

        <div class='player-pos-group' v-for='set in [[0, 3], [1, 2]]'>
          <span class='player-pos' v-for='ix in set'>
            <player v-bind:data='game.players[ix]'
                    v-bind:class='{ current: game.next_to_play == ix }'>
            </player>
            <card v-bind:number="game.current_round.cards[ix]"
                  v-bind:class="{ flipped: playedSetHidden[ix] }">
            </card>
          </span>
        </div>
        <h4 v-if="game.status == 'playing' && game.suit">
          <%= t('game.playing.game_suit') %>
          <span class='info'>
            <span v-bind:class="['suit-' + game.suit]"></span>
          </span>
        </h4>
      </div>
      <div v-if="game.status != 'to_name'">
        <h4>
          <%= t('game.playing.your_hand') %>
          <span v-if="game.status == 'playing' && game.next_to_play == player.index">
            (<%= t('game.playing.your_turn') %>)
          </span>
        </h4>
        <div class='card-set'>
          <card v-for='number in (player.cards || new Array(12))'
                v-bind:number='number'
                v-bind:class="{ flipped: playerCardSetHidden, selected: (selectedCard == number || selectedCards.indexOf(number) >= 0), disabled: !cardEnabled(number) }"
                @click.native='selectCard(number)'>
          </card>
        </div>
      </div>
      <div v-if='game.widow_set && game.widow_set.length > 0'>
        <h4><%= t('game.playing.widow_set') %></h4>
        <div class='card-set'>
          <card v-for='number in game.widow_set'
                v-bind:number='number'
                v-bind:back="null"
                v-bind:class="{ flipped: widowSetHidden, selected: selectedTrumpCards.indexOf(number) >= 0 }"
                @click.native='selectTrumpCard(number)'>
          </card>
        </div>
      </div>
    </div>
    <div v-if="game.status == 'to_deal'">
      <h4><%= t('game.to_deal.title') %></h4>
      <button v-if='player.admin' v-on:click='deal'><%= t('game.to_deal.deal') %></button>
    </div>
    <div v-if="game.status == 'to_bid'">
      <h4><%= t('game.to_bid.title') %></h4>
      <button v-if='player.admin' v-on:click='start_bidding'><%= t('game.to_bid.start_bidding') %></button>
    </div>
    <div v-if="game.status == 'bidding'">
      <h4><%= t('game.bidding.title') %></h4>
      <h4 class='bidding'>
        <div class='my-team'>
          <player v-bind:class='{ current: game.current_bidder == index }' v-bind:data='player' v-for='(player, index) in game.players' v-if='index % 2 == 0'>
            <span v-if='game.bids[index] >= 100' class='info'> {{ game.bids[index] }} </span>
            <span v-else-if='game.bids[index] >= 0'>?</span>
            <span v-else>&empty;</span>
          </player>
        </div>
        <div class='other-team'>
          <player v-bind:class='{ current: game.current_bidder == index }' v-bind:data='player' v-for='(player, index) in game.players' v-if='index % 2 == 1'>
            <span v-if='game.bids[index] >= 100' class='info'> {{ game.bids[index] }} </span>
            <span v-else-if='game.bids[index] >= 0'>?</span>
            <span v-else>&empty;</span>
          </player>
        </div>
      </h4>
      <div v-if='game.current_bidder == player.index'>
        <div>
          <button v-on:click='bidUp()' v-if='(game.highest_bid + bidAmount) < 165'>+</button>
          {{ (game.highest_bid || 100) + bidAmount }}
          <button v-on:click='bidDown()' v-if='bidAmount > 0'>-</button>
        </div>
        <div>
          <button v-on:click='bid' v-if='bidAmount > 0 || game.highest_bid == 0'><%= t('game.bidding.bid') %></button>
          <button v-on:click='pass'><%= t('game.bidding.pass') %></button>
        </div>
      </div>
    </div>
    <div v-if="game.status == 'to_trump'">
      <h4><%= t('game.to_trump.title') %></h4>
      <button v-if='game.highest_bidder == player.index' v-on:click='trump'><%= t('game.to_trump.trump') %></button>
    </div>
    <div v-if="game.status == 'to_play'">
      <h4><%= t('game.to_play.title') %></h4>
      <button v-if='player.admin' v-on:click='start_game'><%= t('game.to_play.start_game') %></button>
    </div>
    <div v-if="game.status == 'done'">
      <h4><%= t('game.done.title') %></h4>
      <button v-if='player.admin' v-on:click='restart'><%= t('game.done.restart') %></button>
    </div>
  </div>
  <div v-else-if="game.status == 'to_name'">
    <button v-on:click='join'><%= t('game.join') %></button>
  </div>
  <div v-else>
    No access
  </div>
</div>